---

- name: 'Download and install.'
  block:
    - name: 'Stat directory.'
      stat:
        get_attributes: false
        get_checksum: false
        get_md5: false
        get_mime: false
        path: '{{ item.dir }}'
      loop: '{{ awsbeats_install }}'
      register: 'awsbeats_stat'
    - name: 'Create directory if does not exist.'
      file:
        group: '{{ item.group }}'
        mode: '{{ item.dirmode }}'
        owner: '{{ item.owner }}'
        path: '{{ item.dir }}'
        state: 'directory'
      loop: '{{ awsbeats_install }}'
      when: 'awsbeats_stat.results
            |selectattr("item.path","eq",item.path)
            |map(attribute="stat")
            |selectattr("exists")
            |list
            |length==0'
    - name: 'Install binary.'
      get_url:
        dest: '{{ item.path }}'
        group: '{{ awsbeats_install_group }}'
        mode: '{{ awsbeats_install_filemode }}'
        owner: '{{ awsbeats_install_owner }}'
        url: '{{ item.url }}'
      loop: '{{ awsbeats_install }}'
  when: 'awsbeats_install_enabled'
